yolo_model:

  config_file:
    name: yolov4-tiny.cfg
  weight_file:
    name: yolov4-tiny.weights
  threshold:
    value: 0.4
  detection_classes:
    names:
      - person
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show
      - dont_show